<a href="https://colab.research.google.com/github/siva12309521/Data-Science-Mini-Projects/blob/main/homeprice(Algorithms).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt


In [ ]:
home = pd.read_csv("/content/drive/MyDrive/data/homeprices (7).csv")

In [ ]:
home

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
home.shape

(5, 2)

In [ ]:
home.isnull().sum()

area     0
price    0
dtype: int64

In [ ]:
home.describe()

area          price
count     5.000000       5.000000
mean   3280.000000  626000.000000
std     540.370243   74949.983322
min    2600.000000  550000.000000
25%    3000.000000  565000.000000
50%    3200.000000  610000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [ ]:
home.tail()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
home.head(2)

area   price
0  2600  550000
1  3000  565000

In [ ]:
plt.xlabel("area")
plt.ylabel("price")
plt.scatter(home.area,home.price,color = "red",marker="*")

In [ ]:
x=home.drop("price",axis="columns")

In [ ]:
x

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [ ]:
y=home.price

In [ ]:
y

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [ ]:
# create linear regression object
reg = linear_model.LinearRegression()

In [ ]:
reg.fit(x,y)

LinearRegression()

In [ ]:
reg.predict([[3300]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [ ]:
reg.predict([[50]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([187405.82191781])

In [ ]:
reg.predict([[2600]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([533664.38356164])

In [ ]:
homeprice = pd.read_csv("/content/drive/MyDrive/data/homeprices (6).csv")

In [ ]:
homeprice

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
homeprice.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [ ]:
plt.xlabel(["area","age","bedrooms"])
plt.ylabel("price")
plt.scatter(home.area,home.price,color = "red",marker="*")

In [ ]:
homeprice1 = homeprice.fillna(homeprice["bedrooms"].median())

In [ ]:
homeprice1

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
homeprice1.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [ ]:
ho=linear_model.LinearRegression()
ho.fit(homeprice1.drop("price",axis="columns"),homeprice1.price)

LinearRegression()

In [ ]:
ho.predict([[600,3,40]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([229458.39091918])

In [ ]:
new= pd.read_csv("/content/drive/MyDrive/data/multilinear_regression_dataset.csv")

In [ ]:
new

Years_of_Experience  Education_Level  Age  Salary
0                    1               12   22   40000
1                    3               14   25   48000
2                    5               16   27   58000
3                    7               16   30   67000
4                    9               18   32   78000
5                   11               18   35   90000
6                   13               20   38  102000
7                   15               20   40  115000
8                   17               22   43  130000
9                   20               22   47  150000

In [ ]:
new.isnull().sum()

Years_of_Experience    0
Education_Level        0
Age                    0
Salary                 0
dtype: int64

In [ ]:
plt.xlabel(["Years_of_Experience","Education_Level","Age"])
plt.ylabel("Salary")
plt.scatter(new.Years_of_Experience,new.Salary,color = "red",marker="*")

In [ ]:
ne=linear_model.LinearRegression()
ne.fit(new.drop("Salary",axis="columns"),new.Salary)

LinearRegression()

In [ ]:
ne.predict([[9,18,40]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([96823.86595832])